version: '3.8'

services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://allen:123456@db:5432/newsapi_production
      RAILS_ENV: production

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: allen
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: newsapi_production
    ports:
      - "5432:5432"