default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: allen
  password: 123456
  host: db
  port: 5432

development:
  <<: *default
  database: newsapi_development

test:
  <<: *default
  database: newsapi_test

production:
  <<: *default
  database: newsapi_production